name: "Release"
on: [push, pull_request] 

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6
    - name: Tag Repo
      uses: richardsimko/update-tag@v1
      with:
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./
      with:
        artifacts: ./action.yml
        removeArtifacts: true
        replacesArtifacts: true
        generateReleaseNotes: true
        replaceReleaseNotes: true
        # bodyFile: QuickPing/Package/CHANGELOG.md
        commit: ${{ steps.branch-name.outputs.current_branch }}
        tag: "latest"
        allowUpdates: true
        updateOnlyUnreleased: true
        name: "Pre-release: ${{ env.GitVersion_SemVer }}"
        prerelease: true